name: "Github Tag Bump (Nix)"
description: "Bump and push git tag on merge"
author: "Nick Sjostrom"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Evaluate
      run: entrypoint.sh
      env:
        BRANCH_HISTORY: ${{ env.BRANCH_HISTORY }}
        CUSTOM_TAG: ${{ env.CUSTOM_TAG }}
        DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}
        DEFAULT_BUMP: ${{ env.DEFAULT_BUMP }}
        DRY_RUN: ${{ env.DRY_RUN }}
        FORCE_WITHOUT_CHANGES: ${{ env.FORCE_WITHOUT }}
        GIT_API_TAGGING: ${{ env.GIT_API }}
        INITIAL_VERSION: ${{ env.INITIAL_VERSION }}
        MAJOR_STRING_TOKEN: ${{ env.MAJOR_STRING }}
        MINOR_STRING_TOKEN: ${{ env.MINOR_STRING }}
        NONE_STRING_TOKEN: ${{ env.NONE_STRING }}
        PATCH_STRING_TOKEN: ${{ env.PATCH_STRING }}
        PRERELEASE: ${{ env.PRERELEASE }}
        PRERELEASE_SUFFIX: ${{ env.PRERELEASE_SUFFIX }}
        RELEASE_BRANCHES: ${{ env.RELEASE_BRANCHES }}
        SOURCE: ${{ env.SOURCE }}
        TAG_CONTEXT: ${{ env.TAG_CONTEXT }}
        VERBOSE: ${{ env.VERBOSE }}
        WITH_V: ${{ env.WITH_V }}
outputs:
  new_tag:
    description: "Generated tag"
  tag:
    description: "The latest tag after running this action"
  part:
    description: "The part of version which was bumped"
branding:
  icon: "git-merge"
  color: "purple"
